---
apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: modern-toolbox-java
servers: 1
agents: 0
image: docker.io/rancher/k3s:v1.21.7-k3s1
registries:
  create:
    name: my-registry
options:
  k3d:
    wait: true
    timeout: "60s"
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
